version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./staticfiles:/home/django_test/static
      - ./mediafiles:/home/django_test/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    networks:
      - prod_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"  # Exposed for local debugging
    volumes:
      - ./:/home/skillnest
    env_file:
      - .env.prod
    environment:
      - PORT=8000  # Explicitly set for local use
    networks:
      - prod_network
    command: /usr/bin/supervisord

networks:
  prod_network:
    external: true