version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillnest
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/skillnest/static
      - prod_media_volume:/home/skillnest/media-files
      - ./:/home/skillnest
    env_file:
      - .env.prod
    image: django_app
    container_name: django_app
    depends_on:
      - postgres
    networks:
      - prod_network
    command: /usr/bin/supervisord

volumes:
  postgres_data:
    external: true
  static_volume:
    external: true
  prod_media_volume:
    external: true

networks:
  prod_network:
    external: true
